
branches:
 only:
   - dev

sudo: false

matrix:
  include:

    - os: osx
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6.3
        - TEST_TOX_ENV=py36
        - COVERAGE_TOX_ENV=coverage-py36
        - BUILD_TOX_ENV=build-py36

    - os: osx
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.5.4
        - TEST_TOX_ENV=py35
        - COVERAGE_TOX_ENV=coverage-py35
        - BUILD_TOX_ENV=build-py35
    - os: osx
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=2.7.14
        - TEST_TOX_ENV=py27
        - COVERAGE_TOX_ENV=coverage-py27
        - BUILD_TOX_ENV=build-py27

cache:
  directories:
    - $HOME/.pyenv/versions/3.6.3
    - $HOME/.pyenv/versions/3.5.4
    - $HOME/.pyenv/versions/2.7.14

before_install:
  - pip install -U scikit-ci-addons
  - ci_addons --install ../addons
  - export PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - python ../addons/travis/install_pyenv.py
  - pyenv global $TRAVIS_PYTHON_VERSION

install:
  - pip install tox-travis tox-pyenv

script:
  - tox -e $TEST_TOX_ENV
  - tox -e $COVERAGE_TOX_ENV
  - tox -e $BUILD_TOX_ENV
  - tox -e $TEST_TOX_ENV recreate --installpkg dist/*-none-any.whl
