build: false

branches:
 only:
  - dev

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON: C:\Miniconda-x64
      EXPECTED_WHEEL: pynwb-0.1-py2-none-any.whl
      ENV: miniconda
    - PYTHON_VERSION: 3.6
      PYTHON: C:\Miniconda36-x64
      EXPECTED_WHEEL: pynwb-0.1-py3-none-any.whl
      ENV: miniconda
    - PYTHON_VERSION: 2.7
      PYTHON: C:\\Python27-x64
      EXPECTED_WHEEL: pynwb-0.1-py2-none-any.whl
      ENV: python
      SCIPY: https://pypi.python.org/packages/f0/5c/bc1e0c17b1fbf6e21827e9da97f2f584d8dc51993717479adff778ba718a/scipy-1.0.0rc2-cp27-none-win_amd64.whl
    - PYTHON_VERSION: 3.6
      PYTHON: C:\\Python36-x64
      EXPECTED_WHEEL: pynwb-0.1-py3-none-any.whl
      ENV: python
      SCIPY: https://pypi.python.org/packages/ed/23/cc831da308cf4f7e319c73e32197a1204daed6ce8c76c741fcaf1903c489/scipy-1.0.0rc2-cp36-none-win_amd64.whl

init:
  - "ECHO %PYTHON% %PYTHON_VERSION%"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - if [%ENV%]==[miniconda] (
      conda config --set always_yes yes --set changeps1 no &&
      conda update -q conda &&
      conda info -a &&
      conda install -c anaconda scipy numpy)
  - if [%ENV%]==[python] (
      pip install wheel &&
      pip install %SCIPY%)

install:
  - pip install -r %APPVEYOR_BUILD_FOLDER%\requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%\requirements-dev.txt
  - python %APPVEYOR_BUILD_FOLDER%\setup.py sdist
  - python %APPVEYOR_BUILD_FOLDER%\setup.py bdist_wheel
  - pip install %APPVEYOR_BUILD_FOLDER%\

test_script:
  - python %APPVEYOR_BUILD_FOLDER%\test.py

after_test:
  - coverage run --source %APPVEYOR_BUILD_FOLDER%\src %APPVEYOR_BUILD_FOLDER%\test.py --pynwb
  - codecov -F pynwb
  - coverage run --source %APPVEYOR_BUILD_FOLDER%\src %APPVEYOR_BUILD_FOLDER%\test.py --integration
  - codecov -F integration
  - coverage run --source %APPVEYOR_BUILD_FOLDER%\src %APPVEYOR_BUILD_FOLDER%\test.py --form
  - codecov -F form
  - pip install -U %APPVEYOR_BUILD_FOLDER%\dist\%EXPECTED_WHEEL%
  - python %APPVEYOR_BUILD_FOLDER%\test.py
  - pip install -U %APPVEYOR_BUILD_FOLDER%\dist\pynwb-0.1.tar.gz
  - python %APPVEYOR_BUILD_FOLDER%\test.py
