build: false

branches:
 only:
  - dev

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON: C:\Miniconda-x64
      ENV: miniconda
    - PYTHON_VERSION: 3.5
      PYTHON: C:\Miniconda35-x64
      ENV: miniconda
    - PYTHON_VERSION: 3.6
      PYTHON: C:\Miniconda36-x64
      ENV: miniconda
    - PYTHON_VERSION: 2.7
      PYTHON: C:\\Python27-x64
      ENV: python
    - PYTHON_VERSION: 3.5
      PYTHON: C:\\Python35-x64
      ENV: python
    - PYTHON_VERSION: 3.6
      PYTHON: C:\\Python36-x64
      ENV: python

init:
  - "ECHO %PYTHON% %PYTHON_VERSION%"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - if [%ENV%]==[miniconda] (
      conda config --set always_yes yes --set changeps1 no &&
      conda update -q conda &&
      conda info -a &&
      conda install -c anaconda numpy)
  - if [%ENV%]==[python] (
      pip install wheel)

install:
  - pip install -r %APPVEYOR_BUILD_FOLDER%\requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%\requirements-dev.txt
  - python %APPVEYOR_BUILD_FOLDER%\setup.py sdist
  - python %APPVEYOR_BUILD_FOLDER%\setup.py bdist_wheel -d %APPVEYOR_BUILD_FOLDER%\dist
  - pip install %APPVEYOR_BUILD_FOLDER%\

test_script:
  - python %APPVEYOR_BUILD_FOLDER%\test.py

after_test:
  - coverage run %APPVEYOR_BUILD_FOLDER%\test.py --pynwb
  - coverage report -m
  - codecov -F pynwb
  - coverage run  %APPVEYOR_BUILD_FOLDER%\test.py --example --integration
  - coverage report -m
  - codecov -F integration
  - coverage run %APPVEYOR_BUILD_FOLDER%\test.py --form
  - coverage report -m
  - codecov -F form
  - ps: (Get-Item $env:APPVEYOR_BUILD_FOLDER\dist\*none-any.whl).Name | ForEach-Object {pip install -U $env:APPVEYOR_BUILD_FOLDER\dist\$_}
  - python %APPVEYOR_BUILD_FOLDER%\test.py
  - ps: (Get-Item $env:APPVEYOR_BUILD_FOLDER\dist\*.tar.gz).Name | ForEach-Object {pip install -U $env:APPVEYOR_BUILD_FOLDER\dist\$_}
  - python %APPVEYOR_BUILD_FOLDER%\test.py
