version: 2
jobs:
   build:
     docker:
       - image: ubuntu:xenial
     steps:
       - checkout
       - run:
           name: Install system requirements
           command: |
             apt-get update
             apt-get install -y software-properties-common python-software-properties
       - run:
           name: Install python3.6 and pip
           command: |
             add-apt-repository ppa:jonathonf/python-3.6
             apt-get update
             apt-get install -y python-pip python3.6
       - run:
           name: Install tox
           command: |
             pip install tox
       - run:
           name: Run the tests for Python 2.7
           command: |
             tox -e py27
       - run:
           name: Run the tests for Python 3.6
           command: |
             tox -e py36
